name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: node-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x

      - name: Build tweego
        run: |
          git clone https://github.com/tmedwards/tweego.git
          cd tweego          
          go get
          go build
          
      - name: Fetch Story-Formats
        run: |
          mkdir story-formats
          cd story-formats
          npm i --prefix ./ https://cdn.jsdelivr.net/gh/klembot/twinejs@2.3.15/story-formats/
          cd ../..
      
      - name: Build book
        run: |
          mkdir dist
          ls -ll
          ./tweego/tweego -f harlowe-1 cooper.tw2 -o dist/index.html
          cp -r images/ dist

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
