name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x

      - name: Use Node.js 12
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '12.x'
        
      - name: Build tweego
        run: |
          git clone https://github.com/tmedwards/tweego.git
          cd tweego          
          go get
          go build
          cd ..
          
      - name: Fetch Story-Formats
        run: |
          npm i --prefix ./ https://cdn.jsdelivr.net/gh/klembot/twinejs@2.3.15/
          ls -ll
          mv ./twinejs@2.3.15/story-formats/ ./story-formats
          ls -ll
      
      - name: Build book
        run: |
          mkdir dist
          ls -ll
          ./tweego/tweego -f harlowe-1 cooper.tw2 -o dist/index.html
          cp -r images/ dist

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
